### ISSUE TITLE
(localize error) VM administrator user name should not be localize.

### ISSUE THREAD

**Issue by dakozu** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp#10]
#### <a name="step-03"></a>step:03

and

#### <a name="step-02"></a>Step:02

VM Administrator user name should not be localize.
We can't use Kanji '学生' for user name. 

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/32472054/ae43d445-274e-4c58-809f-cf610cc82a1d)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
Updated and handedback
