### ISSUE TITLE
Lab04-Task03 issue.

### ISSUE THREAD

**Issue by dakozu** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp#11]
### <a name="task-03"></a>タスク:03

The instruction needs to be changed due to an update of the Azure Portal. The English version has already been updated.
https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/issues/713
https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/commit/bcca0293bd3fa3044e8bcaf867371ac684e51982

The old instruction always causes errors and needs to be updated as soon as possible.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
WWL PM Follow-up needed - these locfiles will need to be handed off so the updates can be viable for the loc langs 
[Query for locfiles for ja-jp](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPkZhbHNlPC9TQVRPPjxTQUxPPlRydWU8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQ29udGVudCBHcm91cDtFcXVhbDtMQUItQVotMTA0PC9RUj48UVIgSWQ9IjMiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0xvY0ZpbGVzO0xhbmd1YWdlO0VxdWFsO0phcGFuZXNlIChKYXBhbik8L1FSPjxRUiBJZD0iNCIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7RmlsZXM7Q29udGVudCBUeXBlO05vdCBFcXVhbDtBcnQ8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d)

**Comment by bckelly** [comment]
we are now continuously publishing this repo, so this issue should now be fixed, along with English content.
