### ISSUE TITLE
Lab01-Task01-Step07 issue

### ISSUE THREAD

**Issue by sumahmud** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp#12]
# <a name="module-01"></a>モジュール: 01
#### <a name="step-07"></a>ステップ:07

懸案事項の説明
Azure portal UI for creating a user has been changed.
Now the user creation page has 4 steps:
基本、プロパティ、割り当て、確認と作成.

**Previously, all steps were placed in a single page. 

再現手順:

1. Go to users under manage section in AAD page and create a new user.
<img width="546" alt="image" src="https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/58412718/2578b2a8-106d-488f-9a48-47a28ee305a6">

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by bckelly** [comment]
this should be fixed now.
