### ISSUE TITLE
Lab01-Task04-Step02-Step06

### ISSUE THREAD

**Issue by sumahmud** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp#13]
# <a name="module-00"></a>モジュール: 01
#### <a name="step-00"></a>ステップ:2, 6

懸案事項の説明
Azure portal UI for creating a user has been changed.
Now the user creation page has 4 steps:
基本、プロパティ、割り当て、確認と作成.

**Previously, all steps were placed in a single page.

再現手順:

Go to users under manage section in AAD page and create a new user.
<img width="532" alt="image" src="https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/58412718/771b712c-b207-4f86-a98b-5e8587d9cc61">

**Comment by chriscarty00** [comment]
Change will need to be reflected in US page and then loc pages

**Comment by sumahmud** [comment]
FYI, Changes are already reflected in US page.
<img width="473" alt="image" src="https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/58412718/363ce82f-52e8-43c1-b38c-33d80ee3c7ec">

**Comment by bckelly** [comment]
this looks fixed to me. Please check.
