### ISSUE TITLE
'Student' as VM user ID must not be translated to Japanese.

### ISSUE THREAD

**Issue by dakozu** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp#15]
Please do not translate the Virtual Machine User ID. Windows does not use 2-byte characters for userID.

Lab05-Ex1-Task3-Step12
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/32472054/2e9df955-3639-4357-b5b1-2454dc944808)

Lab08-Ex1-Task1-Step3
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/32472054/997591a3-a673-4d41-a8ee-7298ffb1fef3)

Lab08-Ex1-Task1-Step14
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/32472054/a39a3389-dacc-43d0-8314-1eef05fb2f89)

Lab08-Ex1-Task5-Step2
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/32472054/294de53a-dc37-4b97-a942-89d0d5e0d7bd)

Lab10-Ex1-Task4-Step3
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/32472054/c411c45b-c702-4036-af78-a02f5d7a4d1c)

Lab10-Ex1-Task6-Step4
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/32472054/bb8cd2d5-f30b-4e5c-b490-673c574e79a7)

Lab11-Ex1-Task6-Step17
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/32472054/8ed0dbed-ce0a-41ff-94ba-3b29471c4ec2)

**Comment by bckelly** [comment]
thank you for providing this feedback. We are looking into the best way to implement the fix, both for now, and so it sticks when content is updated.

**Comment by bckelly** [comment]
thank you, we are working to fix this issue.
