### ISSUE TITLE
VM Password

### ISSUE THREAD

**Issue by DaddyCherry** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp#16]
#### <a name="step-00"></a>ステップ:16

懸案事項の説明
手順の中ではパラメーターファイルのパスワードを参照するように指示されているが、これは以前の方法です。現在の方法は、コマンドによるVM作成時にユーザーがパスワードを指定する手順になっているため、その旨の説明が必要です。

**Comment by chriscarty00** [comment]
issue 
Tasks: 04
Step:16
Description of issue
In the instructions you are instructed to reference the password of the parameter file, but this is the previous method. The current method is a procedure where the user specifies a password when creating a VM with a command, so it is necessary to explain to that effect.

**Comment by chriscarty00** [comment]
Hi [kikukawa9](https://github.com/kikukawa9) ca you let me know on what Lab page you saw this issue?

**Comment by kikukawa9** [comment]
Sorry I couldn’t get your intent. As I mentioned, the wrong instruction is step 16 at task 4 in lab demo 4 which is about creating virtual network.

**Comment by kikukawa9** [comment]
Just in case, Put the wrong instruction image. ![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/60773422/08da844d-60b5-4c61-9e31-1a8d6b933c49)

**Comment by chriscarty00** [comment]
Thanks [kikukawa9](https://github.com/kikukawa9) I have the details now

Here is the English  Text 
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/63402128/4850ad28-817a-495b-95b6-1332a4cd5f3a)

Will assign the WWL Loc PM who can discuss with the writers

**Comment by kikukawa9** [comment]
Thanks Chris for your work.

**Comment by stonezy123** [comment]
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/49666210/08494497-cf2a-4f5e-aa08-b76dad57cdbf)
https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/blob/OLPRODLOC/Instructions/Labs/LAB_04-Implement_Virtual_Networking.md
