### ISSUE TITLE
Screenshots are no available.

### ISSUE THREAD

**Issue by sumahmud** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp#17]
# <a name="module-00"></a>モジュール: 01
#### <a name="step-00"></a>ステップ:N/A

懸案事項の説明
Whenever I click a screenshot, it shows 404 error.
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/58412718/459e5956-6885-4d05-87d3-725ac1405a4e)

再現手順:

1. Go to https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/blob/main/Instructions/Labs/LAB_01-Manage_Entra_ID_Identities.md#%E3%82%A2%E3%83%BC%E3%82%AD%E3%83%86%E3%82%AF%E3%83%81%E3%83%A3%E3%81%AE%E5%9B%B3
1. Click on the screenshot. 
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/58412718/7e6af895-d61c-4264-990e-901d08f5a663)

**Comment by stonezy123** [comment]
fixed.
https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/blob/main/Instructions/Labs/LAB_01-Manage_Entra_ID_Identities.md
