### ISSUE TITLE
Japanese keyword missing

### ISSUE THREAD

**Issue by sumahmud** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp#18]
# <a name="module-00"></a>モジュール: 01
#### <a name="step-00"></a>ステップ:01

懸案事項の説明
The keyword should be "**グループ**" instead of "**Groups**". If you search "Groups" in the Japanese UI, it will not return any results.

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/58412718/b0dae570-0a3c-479f-9333-4c057bd152fa)

再現手順:

1. Search "Groups" in a Japanese UI
1. It will not return any result.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
