### ISSUE TITLE
Wrong keyword to search the role definition

### ISSUE THREAD

**Issue by sumahmud** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp#19]
# <a name="module-00"></a>モジュール: 02
#### <a name="step-00"></a>ステップ:04

懸案事項の説明
The name of the custom role is "**Support Ticket Contributor (Custom)**". So even if I search with the keyword of "**サポート要求共同作成者 (カスタム)**", nothing will be returned. 

Please change the "**サポート要求共同作成者 (カスタム)**" to "**Support Ticket Contributor (Custom)**".

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
