### ISSUE TITLE
Please replace Azure Active Directory with Microsoft Entra ID

### ISSUE THREAD

**Issue by sumahmud** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp#20]
# <a name="module-00"></a>モジュール: 02
#### <a name="step-00"></a>ステップ:00

懸案事項の説明
**Azure Active Directory** has been renamed to **Microsoft Entra ID**. 
Please replace **Azure Active Directory** with **Microsoft Entra ID** in all tasks.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Now, the repo was synced with source.
