### ISSUE TITLE
Change the term to Japanese

### ISSUE THREAD

**Issue by sumahmud** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp#21]
# <a name="module-00"></a>モジュール: 06
#### <a name="step-00"></a>ステップ:03

懸案事項の説明
Please replace "**Deploy a custom template**" with "**カスタム テンプレートからのデプロイ**".
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp/assets/58412718/4a9897f7-2fbd-4bde-a9e8-d8194214ab35)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
