### ISSUE TITLE
Lab 4: Mismatch Between "(US) East US" and "米国東部" in Region Field

### ISSUE THREAD

**Issue by DaddyCherry** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp#95]
# Module: 04
#### Step: 04

Description of issue
The instructions specify selecting "米国東部" as the region, but the Azure portal displays this as "(US) East US." The addition of "(US)" in the portal can confuse learners who are following the instructions, as it differs from the localized term used in the documentation.

Suggested fix:
Update the instructions to match the portal display by including "(US) East US" instead of "米国東部." Alternatively, provide a note clarifying that "(US) East US" in the portal corresponds to "米国東部" in the instructions.

![CleanShot 2024-12-03 at 13 22 33@2x](https://github.com/user-attachments/assets/1a642301-6269-4004-b8e0-eda5c37153e5)

**Comment by staleycyn** [comment]
@DaddyCherry - Is your Issue the translation? The US version shows "(US) East US" and that is what is shown on the image. Do you think users can't understand to select "(US) East US"? This is an Administrator class, and you can select any region.

**Comment by DaddyCherry** [comment]
I have empirically gotten many complaints from Learner regarding lab procedures. More than we can imagine, Learners who are new to Azure labs seem to be stressed by even the slightest imperfection. I believe that we should provide the best possible translated content to provide better learning opportunities.
